# Generated by Django 5.2.7 on 2026-01-02 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0002_initial'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contributions',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_contributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loans',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loans',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='groups.memberships'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membership_transactions', to='groups.memberships'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='transacted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performed_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
