# Generated by Django 5.2.7 on 2026-01-02 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performed_audits', to=settings.AUTH_USER_MODEL),
        ),
    ]
